import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@mantine/core/styles.css';
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";
import { NavbarSimple } from "@/components/NavbarSimple";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <div style={{ display: 'flex' }}>
            <NavbarSimple />
            <div style={{ flexGrow: 1, padding: '1rem' }}>
              {children}
            </div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
